version: "3.9"
services:
  bot:
    image: longedok/statsbot:latest
    environment:
      - SESSION_PATH=/data/stats-bot
    env_file:
      - .env
    stop_signal: SIGINT
    restart: on-failure
    entrypoint: ./startup.sh
    volumes:
      - data:/data
      - ./stats-bot.session:/data/stats-bot.session
      - ./startup.sh:/app/startup.sh
    depends_on:
      - questdb
  questdb:
    image: questdb/questdb
    volumes:
      - questdb:/var/lib/questdb
      - type: bind
        source: server.conf
        target: /var/lib/questdb/conf/server.conf
    ports:
      - "8812:8812" # postresql wire protocol
volumes:
  data:
  questdb:

